contract_index/urls.py
from django.urls import path
from . import views

app_name = 'contract_index'

urlpatterns = [
    path('', views.search, name='top'),
    path('index/', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('addrecord/', views.addrecord, name='addrecord'),
    path('import_csv/', views.import_csv, name='import_csv'),
    path('upload/', views.upload, name='upload'),
    path('upload2/', views.upload2, name='upload2'),
    path('changerecord/', views.changerecord, name='changerecord'),
    # path('company/', views.company, name='company'), 廃止
    path('localcompany/', views.local_company, name='localcompany'),
    # path('pdf_download/', views.pdf_download, name='pdf_download'), 廃止
    # path('changerecord/edit/', views.edit, name='edit'), 廃止
    path('addrecord/add_rec/', views.add_rec, name='add_rec'),
    path('search/searchresult/', views.searchresult, name='searchresult'),
    path('searchresult/', views.searchresult, name='searchresult'),
    path('changerecord/searchresult/', views.searchresult, name='searchresult'),
    path('remote_addr/', views.remote_addr_check, name='remote_addr'),
    path('manage_ll/', views.manage_ll, name='manage_ll'),
    path('restrictlocalcompany/', views.restrictlocalcompany, name='restrictlocalcompany'),
    path('restrictlocalcompanydetails/', views.restrictlocalcompanydetails, name='restrictlocalcompanydetails'),
    path('restrictlocalcompanycopy/', views.restrictlocalcompanycopy, name='restrictlocalcompanycopy'),
    # path('csv_exported/', views.csv_exported, name='csv_exported'), 廃止
    path('confirmation/', views.confirmation, name='confirmation'),
    path('api/ringi_redirect/ringi_no/<ringi_num>', views.redirectRingiNum, name="redirect_ringi_num")
]

indexsite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

admin.site.site_title = '契約書INDEX'
admin.site.site_header = '契約書INDEX 設定'
admin.site.index_title = '設定'

urlpatterns = [
    path('', include('contract_index.urls')),
    path('accounts/', include('django.contrib.auth.urls')), # ログイン認証
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (
        path('', include(debug_toolbar.urls)),
    )

contract_index/models.py
from django.db import models
from django.contrib.auth import get_user_model

# テーブルの定義
class Index(models.Model):
    """
    メインとなる契約書テーブルです。
    """
    # IDは自動生成
    # 契約書名
    contract_title = models.CharField(max_length=500, db_index=True)
    # 締結先_甲 FK
    # signing_target_kou = models.ForeignKey('Company', related_name='signing_target_kou', default=0, on_delete=models.SET_DEFAULT)
    signing_target_kou = models.CharField(max_length=2000)
    # 締結先_乙 FK
    # signing_target_otsu = models.ForeignKey('Company', related_name='signing_target_otsu', default=0, on_delete=models.SET_DEFAULT)
    signing_target_otsu = models.CharField(max_length=2000)
    # 締結日表示用
    signing_date_disp = models.CharField(null=True, blank=True, max_length=200)
    # 締結日
    signing_date = models.DateField(null=True, blank=True, db_index=True)
    # 有効期限表示用
    expiration_date_disp = models.CharField(null=True, blank=True, max_length=200)
    # 有効期限
    expiration_date = models.DateField(null=True, blank=True, db_index=True)
    # 自動更新
    auto_update = models.NullBooleanField(null=True, blank=True)
    # ファイル名
    file_name = models.CharField(null=True, blank=True, max_length=200, db_index=True)
    # PDF
    pdf_path = models.CharField(null=True, blank=True, max_length=2000)
    # 備考
    remarks = models.CharField(null=True, blank=True, max_length=2000)
    # 非表示フラグ
    hidden_flag = models.BooleanField(default=False)
    # 管轄社ID FK
    # local_company_id = models.ForeignKey('LocalCompany', default=0, on_delete=models.SET_DEFAULT)
    # 作成日
    create_date = models.DateTimeField(auto_now_add=True)
    # 最終更新日
    modify_date = models.DateTimeField(auto_now=True)
    # 削除フラグ
    deleted_flag = models.BooleanField(default=False)
    # 作成ユーザー
    create_user = models.CharField(null=True, blank=True, max_length=200)
    # 最終更新ユーザー
    modify_user = models.CharField(null=True, blank=True, max_length=200)
    # 多対多フィールド
    localcompanies = models.ManyToManyField('LocalCompany', through='IndexLocalCompany')
    # 契約終了フラグ
    contract_termination_flag = models.BooleanField(default=False)
    # 契約当事者（締結先甲乙がまとめて入るようになる）
    contract_companies = models.CharField(max_length=2000, default='')
    # 原本区分
    original_classification = models.CharField(null=True, max_length=200)
    # 原本保管場所
    original_storage_location = models.CharField(null=True, max_length=200)
    # 光通信Grpの債務保証有無
    loan_guarantee_availability = models.CharField(null=True, max_length=200)
    # 書面番号
    document_number = models.CharField(null=True, max_length=200)
    # 保管場所URL
    storage_location_url = models.CharField(null=True, max_length=1000)
    # 稟議URL
    ringi_url = models.CharField(null=True, max_length=1000)
    # 稟議番号
    ringi_no = models.CharField(null=True, max_length=100)
    # 相手先法人番号
    partner_corporate_number = models.CharField(null=True, max_length=300)

    def __str__(self):
        # return u"{0}:{1}... ".format(self.id, self.contract_title)
        return self.contract_title

    def get_localcompanies(self):
        '''
        管轄社をリストで返します
        '''
        companies = IndexLocalCompany.objects.filter(index=self)
        return [IndexLocalCompany.local_company for company in companies]

    def ringinolist(self):
        if self.ringi_no:
            return self.ringi_no.split(",")

    def ringiurllist(self):
        if self.ringi_url:
            return self.ringi_url.split(",")

class LocalCompany(models.Model):
    """
    管轄社テーブルです。
    """
    id = models.CharField(max_length=13, primary_key=True)
    # 管轄社名
    local_company_name = models.CharField(max_length=200)
    # 作成日
    create_date = models.DateTimeField(auto_now_add=True)
    # 最終更新日
    modify_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.local_company_name

# 中間テーブル
class IndexLocalCompany(models.Model):
    """
    契約書・管轄社を多対多で処理する中間テーブルです。
    """
    index = models.ForeignKey('Index', related_name='index', on_delete=models.CASCADE)
    local_company = models.ForeignKey('LocalCompany', related_name='local_company', on_delete=models.CASCADE)
    add_flg = models.IntegerField(default=0)
    # def __str__(self):
    #     return self.local_company_name

class RestrictLocalCompany(models.Model):
    """
    ユーザー・管轄社を多対多で処理する中間テーブル。
    """
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    # user_id = models.IntegerField()
    local_company = models.ForeignKey('LocalCompany', related_name='restrict_local_company', on_delete=models.CASCADE)
    # local_company_id = models.IntegerField()


# class Company(models.Model):
#     """
#     会社テーブルです。
#     """
#     # 会社名
#     company_name = models.CharField(max_length=200)
#     # カナ
#     company_kana = models.CharField(max_length=200)
#     # 別名ID(可変長)
#     synonym_id = models.CharField(max_length=200)
#     # # 法人番号
#     # corporation_number = models.BigIntegerField()
#     # 作成日
#     create_date = models.DateTimeField(auto_now_add=True)
#     # 最終更新日
#     modify_date = models.DateTimeField(auto_now=True)

#     def __str__(self):
#         return self.company_name

contract_index/views.py
import ast
import csv
import io
import json
import logging
import math
import os
import re
from datetime import date, timedelta
from io import StringIO, TextIOWrapper
from django.db import transaction
from django.core import serializers
import base64
from django import db
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Prefetch, Q, Count
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import six
import json
from querystring_parser import parser
from collections import OrderedDict
import pprint

# 高速化テスト
# from numba import jit

# from .models import Company
from .models import (Index, IndexLocalCompany, LocalCompany,
                     RestrictLocalCompany)
from .cc_query_helper import make_cc_query, make_cn_query

def original_classification_dict():
    """
    項目「原本区分」の辞書を返します
    """
    return {'1': '紙', '2': 'CS', '3': 'GMO Agree', '4': 'DocuSign', '5': 'データ（クラウドサイン）'}


def original_storage_location_dict():
    """
    項目「原本保管場所」の辞書を返します
    """
    return {'1': '法務部', '2': 'データ保管', '3': '人事管理（出向系）', '4': 'コピー保管'}


def add_condition(order_dict, key, condition):
    if key in order_dict:
        if isinstance(condition, list):
            order_dict[key] += condition
        else:
            order_dict[key] += ',' + condition
    else:
        order_dict[key] = condition

def isalnum_ascii(s):
    return s.isalnum() and len(s) == len(s.encode())

def check_pc_number(s):
    return isalnum_ascii(s) and len(s) == 13

def make_double_slash(s):
    s = s.strip()
    if s != "":
        splitted_array = s.split("/")
        splitted_array = [x for x in splitted_array if x != "" and x.strip() != ""]
        return "/{}/".format(("//").join(splitted_array))
    else:
        return ""

# 各ページへの遷移処理 ---------------------------------------------------------------------

@login_required
def index(request):
    """
    idexへの遷移です。
    """

    info("START1")

    indexes = Index.objects.filter(deleted_flag=False)
    # スーパーユーザでなければ管轄社で表示を絞る
    if not request.user.is_superuser:
        # 管轄社の処理
        lc_list = list()
        src_list = list()
        # 新形式 2019/05/21
        rlc = RestrictLocalCompany.objects.filter(user_id=request.user.id)
        if rlc:
            for r in rlc:
                src_list.append(r.local_company_id)

            for i in IndexLocalCompany.objects.filter(local_company_id__in=src_list):
                lc_list.append(i.index_id)
            indexes = indexes.filter(id__in=lc_list)
    # hidden_flagの処理
    if not request.user.has_perm('contract_index.view_hidden'):
        indexes = indexes.filter(hidden_flag=False)
    # 管轄社カラム用
    if request.user.has_perm('contract_index.read_localcompany'):
        indexes = indexes.prefetch_related('localcompanies')

    content = {
        'name': request.user,
        # 削除フラグは取得しない
        # 'indexes': Index.objects.all(),
        'indexes': indexes,
        'indexes_localCompanies': IndexLocalCompany.objects.all(),
        'result': None,
        'original_classification_dict': original_classification_dict().items(),
        'original_storage_location_dict': original_storage_location_dict().items(),
    }
    return render(request, 'contract_index/index.html', content)


@login_required
def search(request):
    """
    検索への遷移です。
    """
    content = {
        'name': request.user,
        'result': None,
        'localCompanies': LocalCompany.objects.all().order_by('local_company_name'),
        'original_classification_dict': original_classification_dict().items(),
        'original_storage_location_dict': original_storage_location_dict().items(),
    }
    return render(request, 'contract_index/search.html', content)


@login_required
def addrecord(request):
    """
    レコード追加への遷移です。
    """
    
    if request.method == "POST":
        # 管轄社番号のチェック        
        lc_list = request.POST['local_company_number'].split(",")
        if lc_list:
            for lc in lc_list:
                if lc:
                    if not check_pc_number(lc.strip()):
                        content = {
                            'name': request.user,
                            'indexes': [],
                            'indexes_localCompanies': [],
                            'localCompanies': LocalCompany.objects.all().order_by('local_company_name'),
                            'result': "管轄社番号を正しく入力してください",
                            'original_classification_dict': original_classification_dict().items(),
                            'original_storage_location_dict': original_storage_location_dict().items(),
                            'old': request.POST
                        }
                        return render(request, 'contract_index/addrecord.html', content)

        # 日付の精査処理
        # 締結日
        signing_date = ''
        signing_date_disp = ''
        if request.POST['signing_date_y']:
            signing_date_disp += request.POST['signing_date_y']
            if request.POST['signing_date_m']:
                signing_date_disp += '-' + request.POST['signing_date_m']
                if request.POST['signing_date_d']:
                    signing_date_disp += '-' + request.POST['signing_date_d']
                    signing_date = signing_date_disp
                else:
                    signing_date = signing_date = signing_date_disp + '-01'
            else:
                signing_date = signing_date_disp + '-01-01'
        else:
            signing_date_disp = ''
            signing_date = None

        # 有効期限
        expiration_date = None
        expiration_date_disp = ''

        auto_update = None

        # 非開示フラグ

        hidden_flag = 0
        pdf_path = ''
        if request.POST.get('hidden_flag') == 'true':
            hidden_flag = 1
        if request.POST.get('pdf_path'):
            pdf_path = request.POST['pdf_path']

        # 相手先法人番号
        number_array = request.POST['partner_corporate_number'].strip().split(",")
        modified_val = []
        for number_item in number_array:                            
            if not check_pc_number(number_item.strip()):
                content = {
                    'name': request.user,
                    'indexes': [],
                    'indexes_localCompanies': [],
                    'localCompanies': LocalCompany.objects.all().order_by('local_company_name'),
                    'result': "相手先法人番号を正しく入力してください",
                    'original_classification_dict': original_classification_dict().items(),
                    'original_storage_location_dict': original_storage_location_dict().items(),
                    'old': request.POST
                }
                return render(request, 'contract_index/addrecord.html', content)
            modified_val.append(number_item.strip())
        partner_corporate_number = ",".join(modified_val)

        Index(
            pdf_path=pdf_path,
            contract_title=zenhan(request.POST['contract_title']),
            signing_target_kou='',
            signing_target_otsu='',
            contract_companies=zenhan(request.POST['contract_companies']),
            signing_date=signing_date,
            signing_date_disp=zenhan(signing_date_disp),
            expiration_date=expiration_date,
            expiration_date_disp=zenhan(expiration_date_disp),
            auto_update=auto_update,
            file_name='',
            remarks='',
            # 非開示
            hidden_flag=hidden_flag,
            # 原本区分
            original_classification=request.POST['original_classification'],
            # 光通信Grpの債務保証有無
            loan_guarantee_availability=request.POST['loan_guarantee_availability'],
            # 稟議番号
            ringi_no=request.POST['ringi_no'],
            ringi_url='',
            # 書面番号
            document_number=request.POST['document_number'],
            # 原本保管場所
            original_storage_location=request.POST['original_storage_location'],

            deleted_flag=False,
            create_user=request.user.username,
            modify_user=request.user.username,
            partner_corporate_number=partner_corporate_number
        ).save()
        # ログ レコード追加
        info('record is inserted by user id[' + request.session['_auth_user_id'] + '].(' + json.dumps(request.POST,
                                                                                                    ensure_ascii=False) + ')')

        # 管轄社の処理

        # 管轄社番号
        # lc_list = request.POST.getlist('local_company')
        lc_list = request.POST['local_company_number'].split(",")
        if lc_list:
            for lc in lc_list:
                if lc:
                    rec = LocalCompany.objects.filter(id=int(lc))
                    if rec:
                        IndexLocalCompany(
                            index_id=Index.objects.latest('create_date').id,
                            local_company_id=int(lc),
                        ).save()

        # 結果表示
        indexes = Index.objects.filter(deleted_flag=False,
                                    id=Index.objects.latest('create_date').id)
        # スーパーユーザでなければ管轄社で表示を絞る
        # if not request.user.is_superuser:
        #     # 管轄社の処理
        #     lc_list = list()
        #     src_list = list()
        #     # 新形式 2019/05/21
        #     rlc = RestrictLocalCompany.objects.filter(user_id=request.user.id)
        #     if rlc:
        #         for r in rlc:
        #             src_list.append(r.local_company_id)
        #         for i in IndexLocalCompany.objects.filter(local_company_id__in=src_list):
        #             lc_list.append(i.index_id)
        #         indexes = indexes.filter(id__in=lc_list)
                # # print(len(indexes))

        # hidden_flagの処理

contract_index/templates/contract_index/company.html
{% extends 'base.html' %} {% block title %}会社名テーブル{% endblock %} {% block content %}
{% comment %} このページは廃止済みです。 {% endcomment %}
<div class="dropdown">
  <!-- 切替ボタンの設定 -->
  <button type="button" class="btn btn-secondary dropdown-toggle dropmenu" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
    aria-expanded="false">
    ユーザー名:{{ user.get_username }}
  </button>
  <!-- ドロップメニューの設定 -->
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    {% comment %} <a class="dropdown-item" href="#">アカウント設定</a> {% endcomment %}
    <a class="dropdown-item" href="{% url 'logout' %}">ログアウト</a>
    <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="/admin/password_change/">パスワード変更</a>
        {% if perms.contract_index.master %}
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{% url 'admin:index' %}">設定</a>
        {% endif %}
  </div>
  <!-- /.dropdown-menu -->
</div>
<!-- /.dropdown -->

<!-- ヘッダーメニュー -->
<div class="taskbar">
  表示レコード数: {{ companies|length }}
  <form method="post" action="">{% csrf_token %}
    {% if perms.contract_index.csv_export %}<input type="submit" name="export" value="ｴｸｽﾎﾟｰﾄ" class="submit btn btn-warning"></input>{% endif %}
    {% if perms.contract_index.csv_import %}<input type="submit" name="import" value="ｲﾝﾎﾟｰﾄ" class="submit btn btn-warning"></input>{% endif %}
    {% if perms.contract_index.add_record %}<input type="submit" name="addrecord" value="ﾚｺｰﾄﾞ追加" class="submit btn btn-warning"></input>{% endif %}
    <input type="submit" name="search" value="検索ﾓｰﾄﾞ" class="submit btn btn-primary" disabled="disabled"></input>
    <a href="{% url 'contract_index:index' %}" class="submit btn btn-primary">契約書ﾃｰﾌﾞﾙへ</a>
    <input type="submit" name="localCompany" value="管轄社ﾃｰﾌﾞﾙへ" class="submit btn btn-primary" disabled="disabled"></input>
    <input type="submit" name="kouOtsuSwap" value="甲乙入替複製" class="submit btn btn-primary" disabled="disabled"></input>
    <input type="submit" name="searchStart" value="検索実行" class="submit btn btn-primary" disabled="disabled"></input>
    <input type="submit" name="searchStart" value="更新ｲﾝﾎﾟｰﾄ用ｴｸｽﾎﾟｰﾄ" class="submit btn btn-primary" disabled="disabled"></input>
    {% if perms.contract_index.manage_ll %}<a href="{% url 'contract_index:localcompany' %}" name="localcompany" value="管轄社管理" class="submit btn btn-primary">管轄社管理</a>{% endif %}
      {% if perms.contract_index.manage_ll %}<a href="{% url 'contract_index:restrictlocalcompany' %}" name="restrictlocalcompany" value="管轄社制限管理" class="submit btn btn-primary" tabindex="1006">管轄社制限管理</a>{% endif %}
  </form>
</div>
<!-- ヘッダーメニューここまで -->

<table class="table-hover text-center tablesorter" id="sorter">
  <thead>
    <tr>
      <th>会社名</th>
      <th>カナ</th>
      <th>別名ID</th>
      <th>法人番号</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for i in companies %}
    <tr>
      <td nowrap>{{ i.company_name }}</td>

      <td nowrap>{{ i.company_kana }}</td>

      <td nowrap>{{ i.synonym_id }}</td>

      <td nowrap>{{ i.corporation_number}}</td>

      <td nowrap>
        <input type="submit" name="edit_{{ i.id }}" value="編集" class="submit btn btn-warning btn-sm btn-block"></input>
      </td>

    </tr>
    {% endfor %}
  </tbody>
</table>

<script>
    $(function() {
      $('#sorter').tablesorter({
        headers: {
          4: {sorter:false}
        }
      });
    });
</script>

{% endblock %}

contract_index/templates/contract_index/import_csv.html
{% extends 'base.html' %} {% block title %}インポート{% endblock %} {% block content %}
{% comment %} CSVインポート用テンプレートです {% endcomment %}
<!-- ヘッダーメニュー -->
<div id='header'>
  <div class="dropdown">
    <!-- 切替ボタンの設定 -->
    <button type="button" class="btn btn-secondary dropdown-toggle dropmenu" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
      aria-expanded="false">
      ユーザー名:{{ user.get_username }}
    </button>
    <!-- ドロップメニューの設定 -->
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <a class="dropdown-item" href="{% url 'logout' %}">ログアウト</a>
      <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="/admin/password_change/">パスワード変更</a>
        {% if perms.contract_index.master %}
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{% url 'admin:index' %}">設定</a>
        {% endif %}
    </div>
    <!-- /.dropdown-menu -->
  </div>
  <!-- /.dropdown -->

  <div class="taskbar">
    <form method="post" action="">{% csrf_token %}
      {% if perms.contract_index.csv_export %}<button class="btn btn-primary" disabled>ｴｸｽﾎﾟｰﾄ</button>{% endif %}
      {% if perms.contract_index.csv_export %}<button class="btn btn-primary" disabled>ｴｸｽﾎﾟｰﾄall</button>{% endif %}
      {% if perms.contract_index.csv_import %}<a href="{% url 'contract_index:search' %}" class="submit btn btn-primary">ｷｬﾝｾﾙ</a>{% endif %}
      {% if perms.contract_index.add_record %}<input type="submit" name="search" value="ﾚｺｰﾄﾞ追加" class="submit btn btn-primary" disabled="disabled">{% endif %}
      <input type="submit" name="kouOtsuSwap" value="OR検索 行追加" class="submit btn btn-primary" disabled="disabled">
      <input type="submit" name="searchStart" value="検索実行" class="submit btn btn-primary" disabled="disabled">
      <input type="submit" name="searchStart" value="更新ｲﾝﾎﾟｰﾄ用ｴｸｽﾎﾟｰﾄ" class="submit btn btn-primary" disabled="disabled">
      {% if perms.contract_index.write_localcompany %}<a href="{% url 'contract_index:localcompany' %}" name="localcompany" value="管轄社管理" class="submit btn btn-primary">管轄社管理</a>{% endif %}
      {% if perms.contract_index.change_indexlocalcompany %}<a href="{% url 'contract_index:restrictlocalcompany' %}" name="restrictlocalcompany" value="管轄社制限管理" class="submit btn btn-primary" tabindex="1006">管轄社制限管理</a>{% endif %}
    </form>
  </div>
  <div class="alert-primary infobar">
    原則として以下を守ってください。
  </div>
</div>
<!-- ヘッダーメニューここまで -->

<!-- メインコンテンツ -->
<div id='contents'>
  <div class="container">
    <form method="post" action="{% url 'contract_index:upload' %}" enctype="multipart/form-data">{% csrf_token %}
      <h3>新規インポート</h3>
      <p>新たにレコードを挿入します。<br><br>
      CSVの1列目は見出しとして<b>契約書名,契約当事者,締結日,原本区分,契約終了フラグ,光通信Grpの債務保証有無,稟議番号,書面番号,管轄社名,管轄社法人番号,原本保管場所</b>としてください。<br>
      日付は"/"スラッシュで区切ってください。複数の管轄社は","カンマで区切ってください。文字コードはShift-JIS(Excel標準)で問題ありません。<br>
      {% load staticfiles %}<a href="{% static 'contract_index/index_import_format_v3.csv' %}" download="index_import_format_v3.csv">[テンプレートをダウンロード]</a></p>
      <input id="import_new" type="file" style="display:none" name='uploaded_csv' accept="text/csv">
      <div class="input-group">
        <input type="text" id="photoCover" class="form-control" placeholder="select file..." style="max-width: 300px;">
        <span class="input-group-btn"><button type="button" class="btn btn-success" onclick="$('input[id=import_new]').click();">参照</button></span>
        <button type='submit' class="btn btn-info" style="margin: 0 10px;">アップロード</button>
      </div>
    </form>
    <form method="post" action="{% url 'contract_index:upload2' %}" enctype="multipart/form-data">{% csrf_token %}
      <br>
      <h3>更新インポート</h3>
      {% comment %} <p>開発中です。</p> {% endcomment %}
      
      <p>No.で一致した既存のレコードを更新します。<br><br>
      変更したくないカラムにも入力されていることが必要です。（<b>空欄は空に</b>なります。）<br>
      日付は"/"スラッシュで区切ってください。複数の管轄社は","カンマでくぎってください。文字コードはShift-JIS(Excel標準)で問題ありません。<br>
      管轄社一覧に存在しない会社名（<b>大文字小文字全角半角</b>区別されます。）が入力されているとその管轄社は処理から無視されます。<br>
      <p>手順</p>
      <ol>
      <li>更新したいレコードが表示されるように検索。</li>
      <li>更新インポート用エクスポートallを実行してCSVファイルを取得。</li>
      <li>変更したい箇所を変更する。</li>
      <li>このページからアップロードする。</li>
      </ol>
      <input id="import_update" type="file" style="display:none" name='uploaded_csv' accept="text/csv">
      <div class="input-group">
        <input type="text" id="photoCover2" class="form-control" placeholder="select file..." style="max-width: 300px;">
        <span class="input-group-btn"><button type="button" class="btn btn-success" onclick="$('input[id=import_update]').click();">参照</button></span>
        <button type='submit' class="btn btn-info" style="margin: 0 10px;">アップロード</button>
    </form>
  </div>
</div>
<script>
  $('input[id=import_new]').change(function() {
    $('#photoCover').val($(this).val().replace("C:\\fakepath\\", ""));
  });
  $('input[id=import_update]').change(function() {
    $('#photoCover2').val($(this).val().replace("C:\\fakepath\\", ""));
  });
</script>
<!-- メインコンテンツここまで -->
{% endblock %}